services:
  backend:
    build:
      context: ./backend
    ports:
      - "2000:2000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "2001:2001"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
