name: Build Docker Backend Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Build Docker image for backend
        run: |
          docker build -t backend ./backend
          docker save backend > backend.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-image
          path: backend.tar
