# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build Docker Backend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image for backend
        run: |
          docker build -t backend ./backend
          docker save backend > backend.tar
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-image
          path: backend.tar

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build  # depends on build job above
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-image
      - name: Load Docker image
        run: docker load < backend.tar
      - name: Run pytest
        run: docker run --rm backend sh -c "pytest /app/tests"

  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    needs: build  # depends on build job above
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-image
      - name: Load Docker image
        run: docker load < backend.tar
      - name: Run Pylint
        run: docker run --rm backend sh -c "pylint /app --rcfile=/app/.pylintrc"
