name: Daily Trading Logic

on:
  schedule:
    # Schedule to run every weekday at 10:30 PM UTC (11:30 PM CET)
    - cron: '30 22 * * 1-5'
  workflow_dispatch: # Manually trigger the workflow

jobs:
  trading-job:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Navigate to backend repository
    - name: Navigate to Backend Repository
      run: cd backend

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run Trading Script
    - name: Run Trading Script
      run: |
        python -m src/business/trading
