name: Daily Trading Logic

on:
  schedule:
    # Every weekday at 8:00 PM UTC (9:00 PM Norway time)
    - cron: '0 20 * * 1-5'
  workflow_dispatch:

jobs:
  trading-job:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}

    
    steps:
      # 1) Check out your repository so we can modify files (like storage.db)
      - name: Check out repository
        uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # or whichever version you prefer

      # 3) Install dependencies
      - name: Install dependencies
        run: pip install --no-cache-dir -r backend/requirements.txt

      # 4) Run your trading logic
      - name: Run Trading Script
        run: |
          cd backend
          python -m src.business.trading

      # 5) Commit and push updated database
      - name: Commit and push changes
        env:
          GIT_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}    
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add backend/src/storage/storage.db
          git commit -m 'Update SQLite database from daily-trading workflow' || echo "No changes to commit"
          git push https://${GIT_AUTH_TOKEN}@github.com/${{ github.repository }}.git ${{ github.ref }}
