name: Pylint

on:
  workflow_run:
    workflows: ["Build Docker Backend Image"]
    types:
      - completed
    branches:
      - "*"


jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: backend-image
    
    - name: Load Docker image
      run: docker load < backend.tar

    - name: Run Pylint in Docker container
      run: |
        docker run --rm backend-linter sh -c 'find /app -name "*.py" | xargs pylint  --rcfile=/app/.pylintrc'