name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      
    - name: Build Docker image for backend
      run: |
        docker build -t backend-linter ./backend

    - name: Run Pylint in Docker container
      run: |
        docker run --rm -e PYTHONPATH=/app backend-linter pylint $(git ls-files '*.py')